// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPrqYEhqPqQo21jifify9YP8XflDkaqpI',
    appId: '1:564938428115:web:5a376884df461f36274e26',
    messagingSenderId: '564938428115',
    projectId: 'deneme-f13ec',
    authDomain: 'deneme-f13ec.firebaseapp.com',
    databaseURL: 'https://deneme-f13ec-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'deneme-f13ec.appspot.com',
    measurementId: 'G-VT25QZC0WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPXSjx3CrSqoB5CGCuafHAiitE5VZlLmA',
    appId: '1:564938428115:android:5d08c1c29c3ebdb1274e26',
    messagingSenderId: '564938428115',
    projectId: 'deneme-f13ec',
    databaseURL: 'https://deneme-f13ec-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'deneme-f13ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ2KC_CJcjLFAZYFfxwmo9KpR07xTTduw',
    appId: '1:564938428115:ios:46ffe55e8dd2f961274e26',
    messagingSenderId: '564938428115',
    projectId: 'deneme-f13ec',
    databaseURL: 'https://deneme-f13ec-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'deneme-f13ec.appspot.com',
    iosBundleId: 'com.example.flutterfirebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ2KC_CJcjLFAZYFfxwmo9KpR07xTTduw',
    appId: '1:564938428115:ios:93e4c8e25d595d60274e26',
    messagingSenderId: '564938428115',
    projectId: 'deneme-f13ec',
    databaseURL: 'https://deneme-f13ec-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'deneme-f13ec.appspot.com',
    iosBundleId: 'com.example.flutterfirebaseapp.RunnerTests',
  );
}
