name: flutterfirebaseapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  firebase_core: ^2.24.2
  firebase_database: ^10.3.8
  firebase_messaging: ^14.7.9
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.3.0
  sleek_circular_slider: ^2.0.1
  workmanager: ^0.5.2
  audioplayers: ^5.2.1
  alarm: ^3.0.2
  sqflite: ^2.3.0
  intl: ^0.19.0
  fl_chart: ^0.66.0
  data_table_2: ^2.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
  - assets/alarm.mp3
